---
# tasks file for rhel_dnsmasq
- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Create configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
    notify: restart dnsmasq

- name: Make sure it's running
  service:
    name: dnsmasq
    state: started
    enabled: yes
